name: x64-TC

on:
  repository_dispatch:
    types: lx64
  workflow_dispatch:
  #schedule:
  #  - cron: 00 16 * * *

#CI权限
permissions: write-all

jobs:
  build:
    #调用公用编译核心OWRT-TC.yml
    uses: ./.github/workflows/OWRT-TC.yml
    secrets: inherit
    with:
      FIRENAME: lx64
      FIRENAME1: x64
      REPO_URL: https://github.com/coolsnowwolf/lede
      REPO_BRANCH: master
      UPLOAD_RELEASE: true
